name:       luna-shell
version:    "1.2"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src
    dependencies:
        - ansi-wl-pprint
        - async
        - base
        - bimap
        - containers
        - directory
        - filepath
        - layered-state
        - luna-core
        - luna-cpp-containers
        - luna-data-tag
        - luna-debug
        - luna-exception
        - luna-passes
        - luna-project
        - luna-runtime
        - luna-stdlib
        - luna-syntax-text-lexer
        - luna-syntax-text-model
        - luna-syntax-text-parser
        - mtl
        - optparse-applicative
        - path
        - prologue
        - text
        - unordered-containers

executables:
    luna:
        main: src/Main.hs
        ghc-options: -threaded "-with-rtsopts=-N -T"
        dependencies:
            - base
            - luna-shell
            - prologue

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - OverloadedStrings
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - RelaxedPolyRec
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

