version: 2
jobs:
  backend:
    environment:
      GHC_RTS: -M3G
    docker:
      - image: lunalang/luna-core-ci:1.0
    steps:
      - checkout
      - run: stack setup
      - run: stack build -j1 --fast --ghc-options="-pgmc gcc-7" --test

workflows:
  version: 2
  percommit:
    jobs:
      - backend
